![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a maximum score of 800 points. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend.

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [ ]:
# Re-run this cell
import pandas as pd

# Read in the data
schools = pd.read_csv("schools.csv")

# Preview the data
schools.head()

                                         school_name  ... percent_tested
0  New Explorations into Science, Technology and ...  ...            NaN
1                               Essex Street Academy  ...           78.9
2                       Lower Manhattan Arts Academy  ...           65.1
3    High School for Dual Language and Asian Studies  ...           95.9
4      Henry Street School for International Studies  ...           59.7

[5 rows x 7 columns]

In [95]:
schools.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school_name      375 non-null    object
 1   borough          375 non-null    object
 2   building_code    375 non-null    object
 3   average_math     375 non-null    int64
 4   average_reading  375 non-null    int64
 5   average_writing  375 non-null    int64
 6   percent_tested   355 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 20.6+ KB

In [ ]:
"""
Create a pandas DataFrame called best_math_schools containing the "school_name" and "average_math" 
score for all schools where the results are at least 80% of the maximum possible score, sorted by "average_math" in descending order
"""

best_math_schools = schools[["school_name", "average_math"]][
    schools["average_math"] >= 640
].sort_values(by="average_math", ascending=False)

# Preview best_math_schools
best_math_schools

                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683
280                     Brooklyn Technical High School           682
333                        Townsend Harris High School           680
174  High School of American Studies at Lehman College           669
0    New Explorations into Science, Technology and ...           657
45                       Eleanor Roosevelt High School           641

In [ ]:
"""
Identify the top 10 performing schools based on scores across the three SAT sections, storing as a pandas DataFrame called top_10_schools containing the school name and a column named "total_SAT", with results sorted by total_SAT in descending order
"""

schools["total_SAT"] = (
    schools["average_math"] + schools["average_reading"] + schools["average_writing"]
)

top_10_schools = (
    schools[["school_name", "total_SAT"]]
    .sort_values(by="total_SAT", ascending=False)
    .reset_index(drop=True)
    .iloc[:10]
)

# Preview top_10_schools
top_10_schools

                                         school_name  total_SAT
0                             Stuyvesant High School       2144
1                       Bronx High School of Science       2041
2                Staten Island Technical High School       2041
3  High School of American Studies at Lehman College       2013
4                        Townsend Harris High School       1981
5  Queens High School for the Sciences at York Co...       1947
6                     Bard High School Early College       1914
7                     Brooklyn Technical High School       1896
8                      Eleanor Roosevelt High School       1889
9  High School for Mathematics, Science, and Engi...       1889

In [ ]:
"""
Locate the NYC borough with the largest standard deviation for "total_SAT", storing as a DataFrame called largest_std_dev with "borough" as the index and three columns: "num_schools" for the number of schools in the borough, "average_SAT" for the mean of "total_SAT", and "std_SAT" for the standard deviation of "total_SAT". Round all numeric values to two decimal places
"""

boroughs = (
    schools.groupby("borough")
    .agg(
        num_schools=pd.NamedAgg(column="school_name", aggfunc="count"),
        average_SAT=pd.NamedAgg(column="total_SAT", aggfunc="mean"),
        std_SAT=pd.NamedAgg(column="total_SAT", aggfunc="std"),
    )
    .round(2)
)

largest_std_dev = boroughs[boroughs["std_SAT"] == boroughs["std_SAT"].max()]

# Preview largest_std_dev
largest_std_dev

           num_schools  average_SAT  std_SAT
borough
Manhattan           89      1340.13   230.29